package Bank;


/**
* Bank/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mardi 23 octobre 2012 19 h 25 CEST
*/

public interface AccountOperations 
{
  int createAccount ();
  void deleteAccount (int accountnum) throws Bank.AccountPackage.UnknownAccount;
  float makeWithdrawal (int accountnum, float amount) throws Bank.AccountPackage.NotEnoughMoney, Bank.AccountPackage.UnknownAccount;
  float makeDeposit (int accountnum, float amount) throws Bank.AccountPackage.UnknownAccount;
  float getBalance (int accountnum) throws Bank.AccountPackage.UnknownAccount;
} // interface AccountOperations
