package Bank;

/**
* Bank/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mardi 23 octobre 2012 19 h 25 CEST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Bank.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (Bank.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Bank.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Bank.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Bank.AccountHelper.type ();
  }

}
