package Bank;


/**
* Bank/AccountPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mardi 23 octobre 2012 19 h 25 CEST
*/

public abstract class AccountPOA extends org.omg.PortableServer.Servant
 implements Bank.AccountOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAccount", new java.lang.Integer (0));
    _methods.put ("deleteAccount", new java.lang.Integer (1));
    _methods.put ("makeWithdrawal", new java.lang.Integer (2));
    _methods.put ("makeDeposit", new java.lang.Integer (3));
    _methods.put ("getBalance", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Bank/Account/createAccount
       {
         int $result = (int)0;
         $result = this.createAccount ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Bank/Account/deleteAccount
       {
         try {
           int accountnum = in.read_long ();
           this.deleteAccount (accountnum);
           out = $rh.createReply();
         } catch (Bank.AccountPackage.UnknownAccount $ex) {
           out = $rh.createExceptionReply ();
           Bank.AccountPackage.UnknownAccountHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // Bank/Account/makeWithdrawal
       {
         try {
           int accountnum = in.read_long ();
           float amount = in.read_float ();
           float $result = (float)0;
           $result = this.makeWithdrawal (accountnum, amount);
           out = $rh.createReply();
           out.write_float ($result);
         } catch (Bank.AccountPackage.NotEnoughMoney $ex) {
           out = $rh.createExceptionReply ();
           Bank.AccountPackage.NotEnoughMoneyHelper.write (out, $ex);
         } catch (Bank.AccountPackage.UnknownAccount $ex) {
           out = $rh.createExceptionReply ();
           Bank.AccountPackage.UnknownAccountHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // Bank/Account/makeDeposit
       {
         try {
           int accountnum = in.read_long ();
           float amount = in.read_float ();
           float $result = (float)0;
           $result = this.makeDeposit (accountnum, amount);
           out = $rh.createReply();
           out.write_float ($result);
         } catch (Bank.AccountPackage.UnknownAccount $ex) {
           out = $rh.createExceptionReply ();
           Bank.AccountPackage.UnknownAccountHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // Bank/Account/getBalance
       {
         try {
           int accountnum = in.read_long ();
           float $result = (float)0;
           $result = this.getBalance (accountnum);
           out = $rh.createReply();
           out.write_float ($result);
         } catch (Bank.AccountPackage.UnknownAccount $ex) {
           out = $rh.createExceptionReply ();
           Bank.AccountPackage.UnknownAccountHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Bank/Account:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Account _this() 
  {
    return AccountHelper.narrow(
    super._this_object());
  }

  public Account _this(org.omg.CORBA.ORB orb) 
  {
    return AccountHelper.narrow(
    super._this_object(orb));
  }


} // class AccountPOA
