#!/bin/sh

if [ $# -ne 2 ] 
	then echo "usage <$0> arg1 arg2"

else

test=KO

	for i in `ls`
	do
		if [ $i = $1 ] 
		then test=OK
		fi

		if [ $i = $2 ] 
		then 
			echo "L'argument 2 est un fichier du repertoire courant."
			exit 2
		fi

	done

	if [ $test = "KO" ]
	then 
		echo "L'argument 1 n'est pas un fichier du répertoire courant."
		exit 2

	else
		#Création du fichier de nom arg2 et contenant "Bienvenue date(aaaa-mm-jj) utilisateur"
		echo Bienvenue `date +%F` `whoami` > $2

		#Ajout des droits d'exécution à tous les utilisateurs
		chmod a+x $2
	fi
fi
