/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "myservice.h"
#include <stdio.h>
#include <stdlib.h>

void
mycomputation_1( char* host )
{
	CLIENT *clnt;
	void  *result_1;
	char*  mycomputation_null_1_arg;
	response  *result;
	data  mycomputation_addition_1_arg;
	clnt = clnt_create(host, MYCOMPUTATION, VERSION_ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
      mycomputation_addition_1_arg.arg1 = 33;
      mycomputation_addition_1_arg.arg2 = 45;
	result = mycomputation_addition_1(&mycomputation_addition_1_arg, clnt);
	if (result == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("[Client] server returned %u\n",result->result);
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	mycomputation_1( host );
}
