/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "myservice.h"

void *
mycomputation_null_1_svc(void *argp, struct svc_req *rqstp)
{

	static char* result;

	/*
	 * insert server code here
	 */

	return((void*) &result);
}

response *
mycomputation_addition_1_svc(data *argp, struct svc_req *rqstp)
{

	static response  result;

	/*
	 * insert server code here
	 */
	printf("arg1=%u arg2=%u\n",argp->arg1, argp->arg2);
	result.result = argp->arg1 + argp->arg2;

	return(&result);
}
