
* Budget 2013

** Idée
   - budget serré, pas encore de décision de passage au RCE 
   - plus de contrat de recherche (-250 KE)
   - comptes financiers en diminution : équip. informatique, communication (-10 KE), secrétariat général

** Strasbourg
   - subvention 2013 des collectivités locales moins importante que 2010-2012, 260 KE au lieu de 300 KE 
   - inquiétude sur l'augmentation de la refacturation de l'ISU : 
     2012 : 58 KE au lieu de 40 KE prévu
     2013 : prévu 68 KE
     -> étudier les factures et comprendre l'évolution. A discuter avec collectivités réunion du 30/11.

* Infrastructure informatique
   - un nouveau service de listes de diffusion basé sur sympa est en place :
     https://listes.ensiie.fr/wws/
     se connecter avec son identifiant <prenom.nom>@ensiie.fr, même mot de passe que mail, etc.
     -> permet de diffuser, avec archivage des messages, à des groupes ciblés d'utilisateurs 
     
   - un nouveau webmail basé sur Horde est mis en place:
    https://webmail.ensiie.fr/
    se connecter avec son identifiant <prenom.nom>, même mot de passe que mail, etc.
    -> permet de lire son mail ENSIIE avec un navigateur

* Visite CTI
   - le comité sera composé de 3 membres, plus un étudiant venant d'un BDE.
   - template pour les slides a été créé et sera diffusé pour harmonisation des présentations.
