/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chat.h"

bool_t
xdr_message(XDR *xdrs, message *objp)
{

	if (!xdr_int(xdrs, &objp->cli_id))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->timestamp))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->message, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->msg_id))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_msg_list(XDR *xdrs, msg_list *objp)
{

	if (!xdr_array(xdrs, (char **)&objp->msg_list_val, (u_int *)&objp->msg_list_len, 99, sizeof(message), (xdrproc_t)xdr_message))
		return (FALSE);
	return (TRUE);
}
