/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "chat.h"

#define MAX_CLIENTS 2
#define MAX_MSG 3
int index_msg=0;	     /* the pointer to last mesage in queue */		
int msg_id=0;         /* the absolute id of a message (whatever the client) */

/* an array that contains ids of connected clients, or 0 if free */
int clients[MAX_CLIENTS];
message mlist[MAX_MSG];


void *
chat_null_1_svc(void *argp, struct svc_req *rqstp)
{

	static char* result;

	/*
	 * insert server code here
	 */

	return((void*) &result);
}

/**
 * connection operation: returns first available slot, or -1
 * if no available.
 **/
int *connect_1_svc(void *argp, struct svc_req *rqstp)
{

	static int i;
	for (i=0;i<MAX_CLIENTS;i++) 
		  if (!clients[i]) {
			    clients[i]=1; /* update to connected */
			    return(&i);
		  }
	/* if we arrive here, we did not return, which
	   means there was no free slot */
      i=-1;
	printf("[server] max number of connections reached.\n");
	return(&i);
}

/**
 * disconnect smoothly
 **/
int * disconnect_1_svc(int *cli_id, struct svc_req *rqstp) {
	static int  result;
	/* unmark my position */
	clients[*cli_id]=0;
	return(&result);
}

/**
 * send operation
 **/
int *send_1_svc (message *argp, struct svc_req *rqstp) {
	static int  result;
	/* store message in mesage list ... */
      memcpy (argp, &(mlist[index_msg]), sizeof(struct(message)));
	/* ... and assign it a message id */
	mlist[index_msg].msg_id = argp->msg_id;
	index_msg = (index_msg+1) % MAX_MSG;
	msg_id++;          /* glboal counter of messages */
	return(&result);
}

/**
 * refresh operation:
 * return the messages stored whose ids are greater than from_id
 **/
msg_list *refresh_1_svc(int *from_id, struct svc_req *rqstp)
{

      static msg_list  returned_msg_list;
	int i=index_msg;
	int nbmsg=0;
	/* count number of message to return: nbmsg */
	while ((mlist[i].msg_id > *from_id) && (i>=0)) {
		nbmsg++;
		i--;
	}
	returned_msg_list.msg_list_len = (u_int) nbmsg;  
	returned_msg_list.msg_list_val = (message *) malloc(nbmsg * sizeof(struct(message *));
	
	return(&returned_msg_list);
}
