/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MYSERVICE_H_RPCGEN
#define _MYSERVICE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct data {
	u_int arg1;
	u_int arg2;
};
typedef struct data data;
#ifdef __cplusplus
extern "C" bool_t xdr_data(XDR *, data*);
#elif __STDC__
extern  bool_t xdr_data(XDR *, data*);
#else /* Old Style C */
bool_t xdr_data();
#endif /* Old Style C */


#ifdef __cplusplus
extern "C" bool_t xdr_data(XDR *, data*);
#elif __STDC__
extern  bool_t xdr_data(XDR *, data*);
#else /* Old Style C */
bool_t xdr_data();
#endif /* Old Style C */


struct response {
	int somme;
	char retcode;
};
typedef struct response response;
#ifdef __cplusplus
extern "C" bool_t xdr_response(XDR *, response*);
#elif __STDC__
extern  bool_t xdr_response(XDR *, response*);
#else /* Old Style C */
bool_t xdr_response();
#endif /* Old Style C */


#ifdef __cplusplus
extern "C" bool_t xdr_response(XDR *, response*);
#elif __STDC__
extern  bool_t xdr_response(XDR *, response*);
#else /* Old Style C */
bool_t xdr_response();
#endif /* Old Style C */


#define MYCOMPUTATION ((rpc_uint)0x20000001)
#define VERSION_ONE ((rpc_uint)1)

#ifdef __cplusplus
#define MYCOMPUTATION_NULL ((rpc_uint)0)
extern "C" void * mycomputation_null_1(void *, CLIENT *);
extern "C" void * mycomputation_null_1_svc(void *, struct svc_req *);
#define MYCOMPUTATION_ADDITION ((rpc_uint)1)
extern "C" response * mycomputation_addition_1(data *, CLIENT *);
extern "C" response * mycomputation_addition_1_svc(data *, struct svc_req *);

#elif __STDC__
#define MYCOMPUTATION_NULL ((rpc_uint)0)
extern  void * mycomputation_null_1(void *, CLIENT *);
extern  void * mycomputation_null_1_svc(void *, struct svc_req *);
#define MYCOMPUTATION_ADDITION ((rpc_uint)1)
extern  response * mycomputation_addition_1(data *, CLIENT *);
extern  response * mycomputation_addition_1_svc(data *, struct svc_req *);

#else /* Old Style C */
#define MYCOMPUTATION_NULL ((rpc_uint)0)
extern  void * mycomputation_null_1();
extern  void * mycomputation_null_1_svc();
#define MYCOMPUTATION_ADDITION ((rpc_uint)1)
extern  response * mycomputation_addition_1();
extern  response * mycomputation_addition_1_svc();
#endif /* Old Style C */

#endif /* !_MYSERVICE_H_RPCGEN */
