package Bank.AccountPackage;


/**
* Bank/AccountPackage/NotEnoughMoney.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mardi 23 octobre 2012 19 h 25 CEST
*/

public final class NotEnoughMoney extends org.omg.CORBA.UserException
{
  public float balance = (float)0;

  public NotEnoughMoney ()
  {
    super(NotEnoughMoneyHelper.id());
  } // ctor

  public NotEnoughMoney (float _balance)
  {
    super(NotEnoughMoneyHelper.id());
    balance = _balance;
  } // ctor


  public NotEnoughMoney (String $reason, float _balance)
  {
    super(NotEnoughMoneyHelper.id() + "  " + $reason);
    balance = _balance;
  } // ctor

} // class NotEnoughMoney
