package Bank.AccountPackage;


/**
* Bank/AccountPackage/UnknownAccount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mardi 23 octobre 2012 19 h 25 CEST
*/

public final class UnknownAccount extends org.omg.CORBA.UserException
{
  public String reason = null;

  public UnknownAccount ()
  {
    super(UnknownAccountHelper.id());
  } // ctor

  public UnknownAccount (String _reason)
  {
    super(UnknownAccountHelper.id());
    reason = _reason;
  } // ctor


  public UnknownAccount (String $reason, String _reason)
  {
    super(UnknownAccountHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class UnknownAccount
