package Bank.AccountPackage;

/**
* Bank/AccountPackage/UnknownAccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mardi 23 octobre 2012 19 h 25 CEST
*/

public final class UnknownAccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Bank.AccountPackage.UnknownAccount value = null;

  public UnknownAccountHolder ()
  {
  }

  public UnknownAccountHolder (Bank.AccountPackage.UnknownAccount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Bank.AccountPackage.UnknownAccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Bank.AccountPackage.UnknownAccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Bank.AccountPackage.UnknownAccountHelper.type ();
  }

}
