package SimpleComputation;


/**
* SimpleComputation/Operation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* mardi 16 octobre 2012 15 h 55 CEST
*/

public interface Operation extends OperationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operation
