package SimpleComputation;


/**
* SimpleComputation/OperationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* mardi 16 octobre 2012 15 h 55 CEST
*/

public abstract class OperationPOA extends org.omg.PortableServer.Servant
 implements SimpleComputation.OperationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addition", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SimpleComputation/Operation/addition
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.addition (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SimpleComputation/Operation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Operation _this() 
  {
    return OperationHelper.narrow(
    super._this_object());
  }

  public Operation _this(org.omg.CORBA.ORB orb) 
  {
    return OperationHelper.narrow(
    super._this_object(orb));
  }


} // class OperationPOA
