package SimpleComputation;


/**
* SimpleComputation/OperationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* mardi 16 octobre 2012 15 h 55 CEST
*/

abstract public class OperationHelper
{
  private static String  _id = "IDL:SimpleComputation/Operation:1.0";

  public static void insert (org.omg.CORBA.Any a, SimpleComputation.Operation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SimpleComputation.Operation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SimpleComputation.OperationHelper.id (), "Operation");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SimpleComputation.Operation read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SimpleComputation.Operation value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SimpleComputation.Operation narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SimpleComputation.Operation)
      return (SimpleComputation.Operation)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SimpleComputation._OperationStub stub = new SimpleComputation._OperationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SimpleComputation.Operation unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SimpleComputation.Operation)
      return (SimpleComputation.Operation)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SimpleComputation._OperationStub stub = new SimpleComputation._OperationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
