package SimpleComputation;


/**
* SimpleComputation/OperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* mardi 16 octobre 2012 15 h 55 CEST
*/

public interface OperationOperations 
{
  int addition (int a, int b);
} // interface OperationOperations
