#----------------------------------------------
all : server client
#----------------------------------------------
server : server.c
	gcc -Wall -o server  server.c -ltirpc
#----------------------------------------------
client : client.c 
	gcc -Wall -o client client.c -ltirpc 
#----------------------------------------------
clean :
	rm -f *.o server client *~ pok* *.ps
