
* Flux


 |     dipl. |              |                    |                    |           |                                  |
 |     année | 1A           | 2A {ISI/ILC}       | 3A {ISI/ILC}       | diplômés  | double dipl. {ISI/ILC/étr}       |
 |-----------+--------------+--------------------+--------------------+-----------+----------------------------------|
 | 2009-2010 | 9            |                    |                    |           |                                  |
 | 2010-2011 | 19 [a]       | 8(-1)              |                    |           |                                  |
 | 2011-2012 | 18 [b]       | 19                 | 8                  | 5=8-3     |                                  |
 | 2012-2013 | 30 [c]       | 18(-1+1)           | 17(-2)             | 17=17-3+3 |                                  |
 | 2013-2014 | 39 [d]       | 28 (-5+3CF)        | 18(0)              | 17=17-1+1 | {0/0/1}                          |
 | 2014-2015 | 43 [e]       | 30(-9) {17/13}     | 27(-1){5/21}       |           | {1/21/?}                         |
 | 2015-2016 |        
 |-----------+--------------+--------------------+--------------------+-----------+----------------------------------|
 |     année | 1A           | 2A {ISI/ILC/CS/SE} | 3A {ISI/ILC/CS/SE} | diplômés  | double dipl. {ISI/ILC/CS/SE/étr} |
 |-----------+--------------+--------------------+--------------------+-----------+----------------------------------|
 | 2015-2016 | 49+3 redbl ? | {19/7/1/5}    [f]  | 27(-1){8/?}        |           |                                  |
 |-----------+--------------+--------------------+--------------------+-----------+----------------------------------|

 
[a] dont maguet, bronner, paiva, shan wu, sijia zheng, faugeroux
[b] dont paiva, thimothée muller
[c] dont paiva, derlon, merouane elmnabhi, hicham Elbilali
[d] dont milton, mercadiel, 7 départs à Evry
[e]
[f] dont +1 ISI : constitidines, +1 ILC : caron. 3 Redoublants 1A 2014-2105:
Benattou, Bucheit, Taheri 

** Remarques:
- promo 2012:
  1A - 2A : -1: bronner (redoub)
  2A - 3A :  
  dipl. 2012 : -2: Boutry, Roverch DD

- promo 2013 :
  1A - 2A : -1 Paiva, +1 Sun
  2A - 3A : - faugeroux (aband) - Wu (Evry)
  dipl. 2013 : +4: Boutry et Roverch DD, Bronner, Maquin -3: Chobert redoub S5, Zeng, Maguet DD 
  Maguet DD
 

- dipl. 2014 : -1:  Tian redoub S5 (Sorbonne), Muller actuariat, +1: Chobert valide S5
 


            * Diplômés par année de sortie

** Promo 2012 (5)

1.Thibault Dubuisson Ingénieur Logiciel     Abase Strasbourg  
2.Marien Ritzenthaler Analyste/Développeur   CGI  Illkirch
3.Bruno Maury Analyste d'affaires  Héma-Québec Montreal
4.Nicolas Weber Développeur Sféreno Strasbourg
5.Guillaume Sabot Développeur ATOS Lyon     

répartition: Industrie/Service/Petite entreprise innovante =  1/4/1


** Promo 2013 (17)

(entrés en 2009: Boutry, Roverch, Maquin)

1. Leslie Bordonné Conceptrice d’app mobiles e-learning Lomdess Strasbourg   (Innov)
2. Jonathan Bronner Ingénieur Etudes et Développement Sopra Strasbourg       (S)
3. Julien Ernwein Ingénieur Développement EID Strasbourg                     (Indus)
4. Sébastien Azim Développeur Web Novelys Strasbourg                         (Innov)
5. Adrien Bracigliano Ingénieur d’études Davidson  Strasbourg                (S)
6. Jean-François Spatz Ingénieur Logiciel FM Logistics Phalsbourg            (Indus)
7. Luke Bertot Doctorant en informatique Icube, Unistra Strasbourg           (autre)
8. Victor Bahl Ingénieur d’affaires Smile Paris                              (Innov)
9. Lucas Bee Développeur OVH Lille                                           (Indus)
10. Nicolas Maire Développeur 3D Ka-Ra Strasbourg                            (Innov)
11. Fadoua Kawni Ingénieur d’études Davidson  Strasbourg                     (S)
12. Sébastien Chatout Développeur Web SDV Plurimédia Strasbourg              (Indus)
13. Pierre Boutry Doctorant en informatique Icube, Unistra Strasbourg        (autre)
14. Xiayoe Sun Ingénieur Logiciel Beijing, Chine                             (Indus)
15. Chenlong Hu Ingénieur Logiciel Astek Strasbourg                          (S)
16. Emeric Roverch Ingénieur Logiciel/Finance Solucom Paris                  (S)
17. Frédéric Maquin Développeur WhiteQuest Erstein                           (Innov)

répartition: Industrie/Service/Petite entreprise innovante/Autre =  5/5/5/2


** Promo 2014 (18)

(entrés en 2010: Chobert)

1. Paul Chobert - Developer, fivebyfive.io - Londres                        (freelance)
2. Mourad BENGMAH - Ingénieur logiciel - Bluestar solutions - Neuchâtel     (editeur)
3. Xavier CAVARELLI	Davidson - Strasbourg                               (ESN)
5. Saad	EL BANNANI - recherche emploi
6. Vincent De Jonghe - changement de site vers Evry
7. Paul GOUY  - Top Décision (projet de création) - Strasbourg              (Innov)
8. Vincent Kaessle - Top Décision (projet de création) - Strasbourg         (Innov)
9. Paul-Henri KOECK - IOs developper - Strasbourg                           (freelance)
10. Baptiste LAFABREGUE - Talent Business System - Strasbourg               (S)
11. Ismail LAGOUILLY - Sopra - Strasbourg                                   (S)
12. Yaohua LIANG - Ingénieur logiciel, Amadeus - Antibes                    (Indus)
    Christophe PAIVA
13. Guillaume PARAN - Titch (projet de création) - Strasbourg               (Innov)
14. Jonathan RYBAK - Bull Strasbourg                                        (Indus)
15. Lucas SAUREL - AUSY - Strasbourg                                        (ESN)
16. Quentin THENOZ - Développeur - TiZ Strasbourg                           (Innov)
17. Tian TIAN - Apprenti - Schneider Electric - Paris                       (Indus)
18. Léo UNBEKANDT - Scalingo (création) - Strasbourg                        (Innov)

répartition: Industrie/Service/Petite entreprise innovante/Freelance =  4/4/5/2


** Promo 2015 (28)

 Slimane AGOURAM                 Sopra-Steria - Paris                   (S/ESN)
 Steve BENEDICK                  Actimage GmbH - Kehl                   (Editeur)
 Clément CALIN                
 Julien CASARIN                  doctorant CIFRE -                      (doct)
 Noël DEUTSCHMANN                Atos-Bull pour ES - Strasbourg         (S/ESN)
 Arnaud COUCHET                  KLEE Group - Paris                     (Editeur+S)
 Antoine ERNEWEIN                Actimage GmbH - Kehl                   (Editeur)
 Thomas ESCHEMANN                Calyatis - Strasbourg                  (Innov)
 Alan FONDERFLICK                Amaris - Strasbourg                    (S/ESN)
 Maxime HECKEL                   Docker (Tutum) - San Francisco         (Innov)
 Etienne HEITZ                   Actimage GmbH  - Kehl                  (Editeur)
 Youssef NAIT BELKACEM           CapGemini - Suresnes                   (S/ESN)
 Anne MAYER                      Professorat
 Timothee MULLER                 AXA - Paris                            (Indus/Assur)
 Philippe Gaultier               Edge Lab - Lausanne                    (Inuds/FinTech)
 Joris GIRARDOT                  ATOS pour CoE - Strasbourg             (S/ESN)
 Magali GROSS                    In-Datech - Strasbourg                 (Indus/Banque)
 Tristan GUILLEVIN               Actinvision - Strasbourg               (S/ESN)
 Hao PAN                         Thoughtworks - Xi'an                   (Editeur)
 Eleanore PIRRI                  EID - Strasbourg                       (Indus/Banque)
 Soufyane REGRAGUI               SFERENO - Strasbourg                   (Editeur)
 Julien SCHROEDER                SFEIR Est - Strasbourg                 (S/ESN)                  
 Claudia TANASE                  AUSYS - Strasbourg                     (S/ESN)
 Elsa THEUIL                     Actinvision - Strasbourg               (S/ESN)
 Laurent WIESER                  CapCode - Strasbourg                   (S/ESN)
 Ming ZHANG 
 Shuyan ZHANG
 Hugo ZILLIOX                    Sopra-Steria - Strasbourg              (S/ESN)




** Promo 2016 (28 ?)

1. ABRANTES Kévin            Scoledge - Strasbourg         (Innov)
2. AGAG	Mebarek          
3. BAUX	Maxime           Actinvision - Strasbourg      (Editeur)
4. BONNET Cyril              Novembre Comm. - Strasbourg   (Editeur/Comm)
5. BONNET Valentin           - Angoulême ?
6. BUECHER Nicolas           HapticMedia - Strasbourg      (Innov)
7. CHANTELOUP Pierre         HapticMedia - Strasbourg      (Innov)
8. CHASTENET Jonathan         Recherche d'emploi
9. DELOFFRE Mélody
10. EL BACHIRI Redoine        Mina Tjänster Sveridge AB - Götheborg, Suède
    (Innov)
11. FLICK Xavier
11. GRAD Philippe             CAPCOD - Strasbourg          (S/ESN)
12. GUILLIN Florent           CALDERA - Strasbourg         (Editeur)
13. HOUET Corentin            Lomdness - Strasbourg        (Editeur)
14. LE PERLIER Raoul
15. LESPINGAL Pierre          Tour du monde
16. LETOFFE Lætitia           CGI - Bordeaux                (S/ESN)
17. LOPEZ Simon               EID - Strasbourg              (Indus/Banque)
18. MASSET Gabriel            ATOS - Strasbourg             (S/ESN)
19. MAZURKIEWICZ Thomas       SOGETI - Luxembourg           (S/ESN)
20. METZGER Gabriel           DOCADVIZ - Strasbourg         (Innov)
21. NOMINE Guillaume          Scoledge - Strasbourg         (Innov)
22. PALLAS Aurélie
23. PEUCKERT Lisa             CGI - Luxembourg              (S/ESN)
24. SOEN Corentin             Gameloft - Montreal, Canada   (Indus/Jeux)
25. SOLOWIEFF Morgane
26. STAUB Olivier
27. WEBER Florian                         - Luxembourg
28. ZHAO Yuheng               promo 2017 



** Promo 2017

---- ADAM Nicolas             Nicolaudie - Brighton (UK)    (Industrie)
---- ALBERT Louis             thèse INRIA ?
---- BALLEUX Benjamin         ITS Future - Schiltigheim     (ESN)
---- BELLUT Pierrick          CGI - Illkirch                (ESN)
---- BOUCHARD Thibault        Actimage GmbH - Kehl          (Editeur/S)
---- BOUET FRançois           Ecole Théatre
---- CHAROUCHNI Mounir        recherche emploi 
---- CHICOIS Maxime           Actimage - Luxembourg         (ESN)
---- DEMEURE Nestor           Thèse CEA - Saclay           (Recherche)
---- FABRA Mickael            recherche d'emploi
---- FLICK Xavier             Actinvision - Strasbourg      (ESN)
---- GIRARDEAU Adrien         Dalim Software                (Editeur)
---- HAGENBACH Bastien        VIE Engie - Bruxelles   
---- HURTER Johnatan          Scalingo - Strasbourg         (Innov)
---- KOBERSI Pauline          Calyatis - Strasbourg         (Innov)
---- LEDOS Sophie             I-Datech - Schiltigheim       (Innov/Industrie)
---- LE PERLIER Raoul         ATOS - Strasbourg             (ESN)
---- LE ROY Gabrielle
---- LOCQUEVILLE Martin       fin de cursus UCAQ
---- MANDICA Nicolas          ECO-SI - Lyon                 (Industrie)
---- MOIRE Sophie             départ etranger
---- MULL Lucas               I-Datech                      (Innov)
---- NIU Yan                  KPMG - Luxembourg             (Indus/Banque)
---- RUFFION Antoine          fin de cursus UCAQ
---- SITEK Jocelyn            fin cursus etranger
---- STEBE Vincent            Catalyse IT - Illkirch        (Editeur/S)
---- TEODORI Damien           fin de cursus etranger
---- ZHAO Yueng               





* Ventilation embauchés par secteur

#+TBL_FMT
|-------+-----------+---------+---------+-----------+-----------+-----------|
|       | Industrie | Service | Editeur | Innovante | Freelance | Doctorant |
|-------+-----------+---------+---------+-----------+-----------+-----------|
|  2012 |         1 |       4 |         |         1 |         0 |         0 |
|  2013 |         5 |       5 |         |         5 |         0 |         2 |
|  2014 |         3 |       3 |       1 |         5 |         2 |         0 |
|  2015 |         2 |       8 |       5 |         2 |         0 |         1 |
|-------+-----------+---------+---------+-----------+-----------+-----------|
| total |        11 |      20 |       6 |        13 |         2 |         3 |
|       |           |         |         |           |           |           |
#+TBL_FMT

