-include /opt/local/include/LaTeX.mk
-include /usr/include/LaTeX.mk
-include /usr/local/include/LaTeX.mk

all: pr_4032.pdf

pr_451.fb.bbl : pr_4032.tex generalbiblio.bib
	bibtex pr_451.fb
	bibtex pr_451
