package Chat;


/**
* Chat/ServicesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mercredi 17 octobre 2012 15 h 32 CEST
*/

abstract public class ServicesHelper
{
  private static String  _id = "IDL:Chat/Services:1.0";

  public static void insert (org.omg.CORBA.Any a, Chat.Services that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Chat.Services extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Chat.ServicesHelper.id (), "Services");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Chat.Services read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServicesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Chat.Services value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Chat.Services narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Chat.Services)
      return (Chat.Services)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Chat._ServicesStub stub = new Chat._ServicesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Chat.Services unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Chat.Services)
      return (Chat.Services)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Chat._ServicesStub stub = new Chat._ServicesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
