package Chat;

import MessageListHolder;
import MessageListHelper;
import Message;
import MessageHelper;

/**
* Chat/ServicesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mercredi 17 octobre 2012 15 h 32 CEST
*/

public abstract class ServicesPOA extends org.omg.PortableServer.Servant
 implements Chat.ServicesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("send", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Chat/Services/send
       {
         Message m = MessageHelper.read (in);
         Message $result[] = null;
         $result = this.send (m);
         out = $rh.createReply();
         MessageListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Chat/Services:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Services _this() 
  {
    return ServicesHelper.narrow(
    super._this_object());
  }

  public Services _this(org.omg.CORBA.ORB orb) 
  {
    return ServicesHelper.narrow(
    super._this_object(orb));
  }


} // class ServicesPOA
