package Chat;

import MessageListHolder;
import Message;

/**
* Chat/ServicesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mercredi 17 octobre 2012 15 h 32 CEST
*/

public interface ServicesOperations 
{
  Message[] send (Message m);
} // interface ServicesOperations
