package Chat;

/**
* Chat/ServicesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mercredi 17 octobre 2012 15 h 32 CEST
*/

public final class ServicesHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.Services value = null;

  public ServicesHolder ()
  {
  }

  public ServicesHolder (Chat.Services initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.ServicesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.ServicesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.ServicesHelper.type ();
  }

}
