
* Validation du CR du 18/12/2012
  validé  

* Contrat de site

** Document en cours d'élaboration
  Rédaction du contrat par 4 parties prenantes pour l'Alsace: 2 universités, INSA et BNU.
  Elargissement de la consultation sur la première version lors d'une réunion intitulée  
  /Visite contractuelle de site pour 2013-2017/.
  30/01 et 31/01 : présentation du projet et de la démarche, échange 
  Sont invités : 2 univs, CHU, CROUS, INSA, BNU 
                 + ENGEES, ENSAS, CNAM , directeurs scientifiques CNRS, INRA, BRGM.
		 + directeurs scientifiques CNRS, INRA, ....
		 + Eucor, Paul Strauss, plus des dizaines d'autres


   Deux points durs dans le premier texte.
   - recommandation de la fusion collegium SIT avec AlsaceTech
   - réseau Figure
   Après rencontre Marc Renner + président BNU avec A. Beretz (alerté par les écoles de Mulhouse
   à qui la présidence de l'UHA a transmis les deux versions de texte) les 2 points durs ont
   été supprimés du document définitif.

** Discussion

    Différence entre Collegium et AlsaceTech : Collegium concentré sur la pédagogie, mais 
    inclus aussi les labos de recherche.
    Difficulté: AT est une association ne dépendant pas du MENSR et donc sera forcément extérieur au contrat de site.
    AT a en revanche une position vis-à-vis des autorités régionales

    => nécéssité de définir le périmètre d'AT
    définir par la reconnaissance CTI : exclu L'ENSAS, l'EM

* Rencontre AT avec la région
** Région
  rencontre avec Martine Mack
** CUS
  rencontre avec Michel Heibel et Fabienne Wendling
  - soutien ré-affirmé, 
  - remise de la feuille de route 2020 de la CUS pour mise en cohérence du dossier
    de contractualisation (dépôt dossier nov 2013) réponse de principe en décembre.
  - Marc Renner invité à présenter AT en commission

* Pré-programme du séminaire AT 
** dates, lieu
   jeudi 16 et ve 17 mai, Mont Saint-Odile
** ateliers
   + études : ne pas aborder l'aspect interne des études mais la collaboration inter-écoles (e.g projet ingénieur-manager) 
   + monde économique



[*] Collegium Sciences Ingénierie Technologie (SIT)
    
    -Ecole Nationale Supérieure de Physique de Strasbourg (ENSPS) devenue Télécom Physique Strasbourg ;
    -Ecole de Chimie, Polymères et Matériaux (ECPM)
    -Ecole et Observatoire des Sciences de la Terre (EOST)
    -Ecole Supérieure de Biotechnologie de Strasbourg (ESBS)
    -Ecole Nationale du Génie de l’Eau, de l’Environnement de Strasbourg (ENGEES)
    -IUT Robert Schuman
    -IUT Louis Pasteur
    -IUT d'Haguenau.

