/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc2.h"

int valeur=VALUE;

int *
essai_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;


    if ( valeur==*argp )
        result=0;
    else if ( valeur>*argp )
        result=2;
    else 
        result=1;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
init_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result=0;

    valeur=*argp;
	/*
	 * insert server code here
	 */

	return &result;
}
