
#+TITLE: Rapport sur le manuscrit Contributions à la Gestion Décentralisée des Ressources dans les Environnements de Grilles et Cloud
#+AUTHOR: Heitem Abbes



Le  document  décrit  les  travaux  de recherche  réalisées  au  laboratoire  de
recherche  LaTICE  en  collaboration  avec  LIPN depuis  sa  thèse  de  doctorat
en 2009. Ces activités ont pour objectif d’améliorer la conception et la mise en
oeuvre des intergiciels de gestion de ressources de calcul et de données.

* Analyse du document
Le  document  est organisé  en  cinq  chapitres.  Le  premier chapitre  est  une
introduction qui donne le contexte scientifique  dans lequel se situe se travail
et résume les principales contributions.


Le  chapitre deux  brosse ensuite l'évolution,  dans les  dernières décennies,  des systèmes
distribués de calcul, sous le prisme  des concepts et problématiques relatifs au
travail  de recherche  présenté. Ce panorama présente 


Le chapitre 3  décrit une première série de contributions  concernant la gestion
des  données dans  des environnements  décentralisés.  Il  introduit d'abord  la
problématique  de la  gestion  des données  volumineuses  pour des  applications
scientifiques de  type workflow.  Le chapitre  décrit avec du recul,  le premier
travail de l'auteur dans ce domaine, l'intergiciel /BonjourGrid/ (2008). Il fait
le constat que la gestion des  données de BonjourGrid devait être améliorée pour
ques  les applications  manipulant des  données volumineuses  puissent passer  à
l'échelle.  Cette fonctionnalité initialement traitée comme une tâche auxiliaire
du  coordinateur,  fait  l'objet  d'une  refonte  pour  devenir  une  composante
/gestionnaire  de  données/  à  part   entière  de  l'intergiciel.   De  manière
pertinente, l'auteur a choisi de s'appuyer  sur des projets existants (BitDew et
Stork) pour réaliser  cette composante. Disposer d'un gestionnaire  de données a
permis de  concevoir des solutions  de cache  et de pré-chargement  des données,
indépendantes de l'intergiciel (l'auteur l'a intégré dans BonjourGrid mais aussi
dans Condor). Le calcul du pré-chargement de données, étant donné un workflow de
tâches (exprimant les  dépendances) est un problème tout à  fait général, que le
document aurait pu mettre davantage en  exergue. Ces travaux sur le gestionnaire
de  données  ont  fait  l'objet d'évaluations  expérimentales  conséquentes  (de
l'ordre  de 200  machines) sur  une  plate-forme réelle,  Grid'5000.  C'est  une
démarche  qu'il faut  saluer  car elle  demande  beaucoup de  temps  de mise  au
point. Elle me semble cependant nécessaire pour avoir une validation crédible de
la proposition.

Toujours en matière de gestion décentralisée des données, ce chapitre expose des
travaux sur la  sécurisation des données dans le cadre  d'un framework MapReduce
par un  mécanisme de  dissémination des  données. La  motivation aurait  pu être
donnée au début de l'exposé (et non  au sein du descriptif du fonctionnement, en
section 3.6.2.6) car cette problématique est  d'importance quand on fait appel à
des ressources de  calcul et stockage externes. En effet,  il est ainsi possible
de  ne confier  aux  entités externes  de stockage  qu'une  partie des  données,
rendant impossible leur compréhension sans les parties complémentaires hébergées
sur des entités de confiance. Cette problématique est complètement en phase avec
l'utilisation grandissante  des clouds publics.  Pour ce travail  également, des
expérimentations conséquentes sur Grid'5000 ont permis  de mesurer le coût de la
surcouche de dissémination.


* Ch 4 Modèles décentralisés de gestion des points de reprises de conteneurs

Le chapitre 4 traite de la tolérance aux pannes par un mécanisme de /check-point
and  restart/  pour  des  applications  s'exécutant  dans  un  environnement  de
/containers/. Ce  thème de  recherche est  particulièrement d'actualité  avec le
développement  des  datacenters,  et  de nombreux  chercheurs  de  la  recherche
académique ou industrielle  y travaillent. Ce chapitre  comporte une description
des travaux relatifs  tout à fait conséquente et précise,  montrant bien comment
se situe  la recherche  de l'auteur. L'originalité  de l'approche  présentée ici
réside dans  le stockage des points  de reprise de manière  décentralisée (alors
que ce  stockage est  traditionnellement fait sur  un support  centralisé réputé
fiable) ainsi que l'ajout d'un mécanisme  de /garbabe collector/, qui élimine au
fur et à  mesure les checkpoints périmés. La distribution  des check-points dans
le système  est opérée  avec une  table de hashage  distribuée.  Cette  table de
hashage  repose  sur  un  logiciel  ouvert  éprouvé  (Cassandra),  modifié  pour
s'adapter  à   la  gestion  des  snapshots   et  la  détection  de   pannes  des
hôtes. L'approche est difficile techniquement  mais ambitieuse car la sauvegarde
de containers offre  une solution générique pour tout  type d'application.  Pour
ce  travail encore,  des expérimentations  menées grâce  à Grid'5000  renforcent
considérablement la validité de la proposition.



Le dernier  chapitre du manuscrit  est consacré aux conlusions  et perspectives.
Les perspectives font  état des pistes à court terme,  qui visent l'amélioration
du mécanisme  de tolérance aux  pannes par  /check-point and restart/.  Une part
conséquente  du chapitre  aborde également  des  perspectives de  moyen et  long
termes. Les idées présentées font apparaître,  en particulier pour ce qui est de
l'utilisation  de navigateurs  comme  noeud  de calcul  et  stockage, une  vraie
conviction personnelle et enthousiasmante de l'auteur.



* Conclusion

Le manuscrit retrace  les travaux de recherche menés par  Heitem Abbes depuis sa
thèse ainsi  que pendant les dix  années qui ont  suivies.  Lors de sa  thèse de
doctorat,  effectuée  en co-tutelle  entre  l'Ecole  Nationale des  Sciences  de
l'Informatique à Tunis  et le LIPN à  Paris 13, Heitem a  pleinement contribué à
construire une collaboration fructueuse et pérenne avec les chercheurs français.
Il est remarquable qu'Heitem ait réussi  à animer cette collaboration durant ces
années  en dépit  de l'éloignement  géographique  et des  charges lourdes  d'une
fonction  d'enseignant.  Ses  publications  pendant cette  période montrent  que
Heitem a su faire  évoluer ses recherches avec l'état de  l'art du domaine, tout
en gardant  le fil  conducteur de  la gestion  décentralisée des  traitements et
données dans les  systèmes distribués.  Les publications  montrent également que
dans  l'évolution de  ses  recherches, Heitem  a su  faire  naitre de  nouvelles
collaborations tout  à fait naturelles  avec d'autres chercheurs français.  Il a
également co-encadré trois doctorants tunisiens.

Au final, Heitem Abbes fait dans son manuscrit une bonne synthèse de son
activité de recherche depuis son doctorat. Il fait apparaitre un fil conducteur
autour duquel il résume avec recul les points importants d'une recherche ayant
évolué avec les problématiques les plus actuelles qui intéressent la
communauté. Ce parcours de recherche a donné lieu à de nombreuses publicatons,
dont 9 articles dans des revues internationales et une quinzaine de publications
dans des conférences internationales de haut niveau.

Pour toutes les raisons évoquées ci-dessus, je suis favorable à la soutenance de
son habilitation à diriger les recherches de l’université Sorbonne Paris Nord.
   





* Questions
- Q chap4 : sauvegarde differentielle des checkpoints ?



* Verbatim

5.4 Moyen et long termes............................. 73
5.4.1 Cloud volontaire à base de navigateurs . . . . . . . . . . . . . . . 73

L’idée d’avoir un cloud volontaire décentralisé, basé sur la participation de navigateurs Web, soulève plusieurs questions : pouvons nous réutiliser les intergiciels, comme Boinc ou Condor, ou faut-il coder de nou- veaux intergiciels s’exécutant sur les navigateurs à base de JavaScript ?


5.4.2 Modèle de préchargemenent/déchargement pour les plateformes mobiles ................................ 74

L’objectif est de décharger les tâches de calcul et les données à partir des appa- reils mobiles vers les nœuds du Cloud
-> Litterture

5.4.3 Découverte des ressources dans les environnements IoT . . . . . . 74
5.4.4 Cloud of Things(CoT)........................ 75
5.4.5 Infrastructures orientées données .................. 76
5.4.6 Calcul orienté services ........................ 78
5.4.7 Efficacitéénergétique......................... 79
5.4.8 Intégrationdeblockchainaveclecloud . . . . . . . . . . . . . . . 80
