/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "chat.h"
#define MAX_MSG_SIZE 256

int  my_last_msg=0; /* latest message i sent */


/**
 * display
 * request the server to return messages youngest than 'from'. 
 * @param myid my lcient id, used to hide my own messages
 * @param from the id of the oldest message
 * @param to the id of the newest message
 **/
void display( int myid, int *from, CLIENT *clnt ) {
	msg_list  *ml;
      int i;

	ml = refresh_1( from, clnt);
	if (ml != NULL) { /* if no message => ml==NULL */
		  for (i=0;i<ml->msg_list_len;i++) {
			 if (myid != ml->msg_list_val[i].cli_id) /* do not show my own messages */
				   printf("client #%d says ->  %s\n",ml->msg_list_val[i].cli_id,
						  ml->msg_list_val[i].message);
		  }
	}
}

/**
 * Grab the messages at the keyboard and send them to the server.
 * @param myid the number of the connected client (only for info)
 * @param clnt the generated structure from rpcgen to handle connection to the server
 * @return none
 **/
void messaging(int myid, CLIENT *clnt) {
	int  *newest_msg;  /* latest message id produced in the system */ 
	char *inputmsg;
	message  send_1_arg;

	printf("..:: Welcome client #%d. Type your message. Empty line to quit. ::..\n\n",myid);
	inputmsg = malloc(MAX_MSG_SIZE);
	strcpy(inputmsg,"init");
	while (inputmsg[0] != '\0') {
		  printf("client-%d> ",myid);
		  inputmsg = fgets(inputmsg,MAX_MSG_SIZE,stdin);
		  /* overwrite trailing \n with a \0 
		   * strlen(inputmsg)>=2 since contains at least 1 char + \0 from fgets*/
		  inputmsg[strlen(inputmsg)-1]='\0';
		  if (strlen(inputmsg)) {  
			    send_1_arg.message = inputmsg;
			    send_1_arg.cli_id = myid;
			    /* send message, and server returns the newest message id
			     * produced in the system (maybe by another client) */
			    newest_msg = send_1(&send_1_arg, clnt);
			    if (newest_msg == NULL) 
					clnt_perror(clnt, "call failed:");
			    else {
					if (*newest_msg > my_last_msg+1) { 
						  /* there are messages produced by others 
						   * since my last message. */
						  display( myid, &my_last_msg, clnt );
						  my_last_msg = *newest_msg; /* update */
					}
			    }
		  }
	}
	free(inputmsg);
}

void
chat_1( char* host )
{
	CLIENT *clnt;
	void  *result_1;
	char  *chat_null_1_arg;
	int   *retcode;
	int   myid;
	char  *connect_1_arg;
	int  *result_3;
	clnt = clnt_create(host, CHAT, VERSION_ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	/* First, connect to the server to retrieve an id */
	retcode = connect_1((void*)&connect_1_arg, clnt);
	if (retcode == NULL) {
		clnt_perror(clnt, "call failed:");
	}
      else {
		 myid = *retcode;
		 if (myid==-1) {
		 	printf("[client] could not get an id from the server (too many clients?)\n");
			exit(-1);
		 }
		 else 
		 	printf("[client] i am connected with id=%d\n",myid);
      }
      /* iterate to get input message until an empty string is entered */
      messaging( myid, clnt );

      /* finally, gently disconnect to make room */ 
	result_3 = disconnect_1(&myid, clnt);
	printf("[client] disconnecting from server ...\n");
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	chat_1( host );
}
