/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	int cli_id;
	char *message;
	int msg_id;
};
typedef struct message message;


typedef struct {
	u_int msg_list_len;
	message *msg_list_val;
} msg_list;

#define CHAT 0x20000001
#define VERSION_ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define CHAT_NULL 0
extern  void * chat_null_1(void *, CLIENT *);
extern  void * chat_null_1_svc(void *, struct svc_req *);
#define CONNECT 1
extern  int * connect_1(void *, CLIENT *);
extern  int * connect_1_svc(void *, struct svc_req *);
#define DISCONNECT 2
extern  int * disconnect_1(int *, CLIENT *);
extern  int * disconnect_1_svc(int *, struct svc_req *);
#define SEND 3
extern  int * send_1(message *, CLIENT *);
extern  int * send_1_svc(message *, struct svc_req *);
#define REFRESH 4
extern  msg_list * refresh_1(int *, CLIENT *);
extern  msg_list * refresh_1_svc(int *, struct svc_req *);
extern int chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CHAT_NULL 0
extern  void * chat_null_1();
extern  void * chat_null_1_svc();
#define CONNECT 1
extern  int * connect_1();
extern  int * connect_1_svc();
#define DISCONNECT 2
extern  int * disconnect_1();
extern  int * disconnect_1_svc();
#define SEND 3
extern  int * send_1();
extern  int * send_1_svc();
#define REFRESH 4
extern  msg_list * refresh_1();
extern  msg_list * refresh_1_svc();
extern int chat_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_msg_list (XDR *, msg_list*);

#else /* K&R C */
extern bool_t xdr_message ();
extern bool_t xdr_message ();
extern bool_t xdr_msg_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
