
/**
* Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mercredi 17 octobre 2012 15 h 32 CEST
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public int cli_id = (int)0;
  public int msg_id = (int)0;
  public String msg = null;

  public Message ()
  {
  } // ctor

  public Message (int _cli_id, int _msg_id, String _msg)
  {
    cli_id = _cli_id;
    msg_id = _msg_id;
    msg = _msg;
  } // ctor

} // class Message
