
/**
* MessageListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mercredi 17 octobre 2012 15 h 32 CEST
*/

public final class MessageListHolder implements org.omg.CORBA.portable.Streamable
{
  public Message value[] = null;

  public MessageListHolder ()
  {
  }

  public MessageListHolder (Message[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MessageListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MessageListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MessageListHelper.type ();
  }

}
